"use client";

import React, { useState } from "react";
import InitialConversation from "./_component/initial-conversion";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import Question from "./_component/question";
import BotResponseUI from "./_component/bot-response";
import InputeGenerationField from "@/components/input-generation-field";

interface Message {
  role: string;
  content: string;
}

const content = {
  listOfGeneratedUI: [
    {
      backgroundColor: "#c9d2d8",
      device_type: "desktop",
      user_rating: 0,
      title: null,
      is_public: true,
      designId: "string",
      designMapping: "string",
      screenshot_url:
        "https://cdn.usegalileo.ai/screenshots/578a5fd2-1f53-4583-a981-244e11263892.webp",
      feed_image_url:
        "https://cdn.usegalileo.ai/feed-images/805d4596-2d2a-4daf-bad4-76d51404c25b.webp",
      thumbnail_url:
        "https://cdn.usegalileo.ai/thumbnails/925c13ea-5830-4580-b35f-e0430d743ed7.webp",
      dimensions: {
        width: 1280,
        height: 2504,
      },
      theme: {
        font: "workSans",
        roundness: 3,
        preset: null,
        primaryColor: "#1f89e0",
        secondaryColor: null,
        saturation: 2,
        lightColors: null,
        darkColors: null,
        mode: "dark",
        autoGenerated: true,
      },
      completed_at: "2024-07-21T06:13:44.849771",
    },
    {
      backgroundColor: "#c9d2d8",
      device_type: "desktop",
      user_rating: 0,
      title: null,
      is_public: true,
      designId: "string",
      designMapping: "string",
      screenshot_url:
        "https://cdn.usegalileo.ai/screenshots/198f2d56-3ef2-45ea-8282-c6aa56083154.webp",
      feed_image_url:
        "https://cdn.usegalileo.ai/feed-images/a3722d6a-318c-4f83-bcb2-c4f51dba1d7e.webp",
      thumbnail_url:
        "https://cdn.usegalileo.ai/thumbnails/3a927699-2516-4052-80f6-1e8aae4369f4.webp",
      dimensions: {
        width: 1280,
        height: 2504,
      },
      theme: {
        font: "workSans",
        roundness: 3,
        preset: null,
        primaryColor: "#1f89e0",
        secondaryColor: null,
        saturation: 2,
        lightColors: null,
        darkColors: null,
        mode: "dark",
        autoGenerated: true,
      },
      completed_at: "2024-07-21T06:13:44.849771",
    },
  ],
  markdownExplanation: "",
};

function page() {
  const [conversation, setConversation] = useState<Message[]>([]);
  const [input, setInput] = useState<string>("");

  return (
    <>
      {conversation.length! > 0 ? (
        <InitialConversation />
      ) : (
        <div className="bg-[#262626] ml-[150px] w-full h-screen relative flex flex-col  items-center">
          <div className="relative h-full w-[65%] flex flex-col justify-center items-center">
            <div className="h-full mb-3  overflow-y-scroll pb-[100px] w-[90%] text-">
              <Question
                name="Adarsh Kumar Singh"
                avatarUrl="https://images.unsplash.com/photo-1623582854588-d60de57fa33f?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGF2YXRhcnxlbnwwfHwwfHx8MA%3D%3D"
                text={
                  "A profile page for japanese inspired store for cool ceramics that feature the history of maker and ceramics for sale, make the color light orange"
                }
              />
              <BotResponseUI content={content} />
            </div>

            <div className="w-full absolute bottom-2 flex flex-row justify-center items-center">
              <InputeGenerationField className="!w-full" />
            </div>
          </div>
        </div>
      )}
    </>
  );
}

export default page;
